### ISSUE TITLE
How to register multiple Redis client instances with Typescript

### ISSUE THREAD

**Issue by CloudPower97** [fastify/fastify-redis#102]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19.2

### Plugin version

4.3.1

### Node.js version

v14.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

I'm trying to register multiple Redis client instances as follow:

```typescript
export default fp<FastifyRedisPlugin>(async (fastify) => {
  await fastify
    .register(fastifyRedis, {
      host: fastify.config.REDIS_HOST,
      port: fastify.config.REDIS_PORT,
      password: fastify.config.REDIS_PASSWORD,
      namespace: 'hello',
    })
    .register(fastifyRedis, {
      host: fastify.config.REDIS_HOST,
      port: fastify.config.REDIS_PORT,
      password: fastify.config.REDIS_PASSWORD,
      namespace: 'world',
    });
}
```

I would expect that, as explained in the docs, I would be able to do something like that:

````typescript
// Here we will use the `hello` named instance
fastify.get('/hello', (req, reply) => {
  const { redis } = fastify

  redis.hello.get(req.query.key, (err, val) => {
    reply.send(err || val)
  })
})

fastify.post('/hello', (req, reply) => {
  const { redis } = fastify

  redis['hello'].set(req.body.key, req.body.value, (err) => {
    reply.send(err || { status: 'ok' })
  })
})

// Here we will use the `world` named instance
fastify.get('/world', (req, reply) => {
  const { redis } = fastify

  redis['world'].get(req.query.key, (err, val) => {
    reply.send(err || val)
  })
})
````

But whenever I try to access `redis['hello']` TypeScript complains about that with the following error:
````
Element implicitly has an 'any' type because expression of type '"hello"' can't be used to index type 'Redis'.
  Property 'hello' does not exist on type 'Redis'.
````

I thought that maybe I would have been able to fix this issue by myself doing that, albeit this is not documented anywhere:

````typescript

import type { Redis } from 'ioredis'

declare module 'fastify' {
  interface FastifyInstance {
    redis: {
      hello: Redis;
      world: Redis;
    };
  }
}
````

But this time TypeScript greets me with this error:

```
Subsequent property declarations must have the same type.  Property 'redis' must be of type 'Redis', but here has type '{ test: Redis; test2: Redis; }'.
```

So this seems a dead end to me.

Can someone shed a light on this for me?

Thanks in advance.

### Steps to Reproduce

Just follow the [Registering multiple Redis client instances](https://github.com/fastify/fastify-redis#registering-multiple-redis-client-instances) step in Readme.MD with a project bootstrapped with [fastify-cli](https://github.com/fastify/fastify-cli) and `TypeScript`.

### Expected Behavior

I expect that one can register multiple Redis instances and correctly access them, even when using `TypeScript`.

**Comment by Eomm** [comment]
I think there is a bug in our types

Looking at mongodb, that it should works 

https://github.com/fastify/fastify-mongodb/blob/23c460cbe8269ebe36612f9ae7fec5cf3c6df600/index.d.ts#L48

Here, this logic is missing

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

cc @fastify/typescript
