### ISSUE TITLE
ERR_AVVIO_PLUGIN_TIMEOUT when run in a jest test

### ISSUE THREAD

**Issue by mishoboss** [fastify/fastify-redis#129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

4.3.3

### Node.js version

16.13.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Docker alpine

### Description

Not sure if it's a bug or not, but it's a strange issue for sure. I'm not able to make fastify-redis work on jest, but I can run it otherwise successfully on the node server. What I get using jest is this:

```
ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /usr/src/app/node_modules/fastify-redis/index.js. You may have forgotten to call 'done' function or to resolve a Promise
        at Timeout._onTimeout (/usr/src/app/node_modules/avvio/plugin.js:123:19)
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7) {
      code: 'ERR_AVVIO_PLUGIN_TIMEOUT',
      fn: <ref *1> [Function: fastifyRedis] {
        default: [Circular *1],
        fastifyRedis: [Circular *1],
        [Symbol(skip-override)]: true,
        [Symbol(fastify.display-name)]: 'fastify-redis',
        [Symbol(plugin-meta)]: { fastify: '>=1.x', name: 'fastify-redis' }
```

This is how I register it:

```
 app.register(fastifyRedis, {
    host: getConfig("REDIS_HOST"),
    port: Number(getConfig("REDIS_PORT")),
    password: getConfig("REDIS_PASSWORD"),
    db: 0,
  });
```

The way I run it in the test:
```
describe("Testing /users endpoints", () => {
  beforeAll((done) => {
    app.ready(async (error) => {
      console.debug("++++ PLUGIN ERROR", error);  <-- this is where I log above error
      try {
        // code I execute here needs fully loaded fastify with all the plugins
        done();
      } catch (e) {
        done(e);
      }
    });
  });
```

This only happens on jest environment. When I run the fastify server everything works like a charm.

### Steps to Reproduce

1. Register fastify-redis
2. Run it in jest test

**Comment by climba03003** [comment]
I would check the value of `getConfig` first.
Then, check if the `redis` instance available on test environment.

**Comment by mikepan-ovoenergy** [comment]
Redis instance is available and getConfig is getting the correct values for host, port and password.

**Comment by mishoboss** [comment]
Redis instance is available and getConfig is getting the correct values for host, port and password.

**Comment by climba03003** [comment]
Then I would recommend you to provide a runable repro.
Not only with the `.register` line.

**Comment by kkkkh** [comment]
Has the problem been solved? I had the same problem today.
