### ISSUE TITLE
TypeScript error when using Redis.Cluster from ioredis

### ISSUE THREAD

**Issue by jimmy-guzman** [fastify/fastify-redis#162]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

6.0.0

### Node.js version

16.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5

### Description

Let's say we're using an existing `Redis.Cluster` client we get the following TypeScript error

```
    Type 'Redis | Cluster' is not assignable to type 'Redis'.
      Type 'Cluster' is not assignable to type 'Redis'.
```

### Steps to Reproduce

```ts
import fastifyRedis from "@fastify/redis";
import fastify from "fastify";
import Redis from "ioredis";

const instance = fastify();

const client = new Redis.Cluster([{ host: REDIS_HOST, port: REDIS_PORT }], {
  redisOptions: { password: REDIS_PASSWORD },
});

instance.register(fastifyRedis, {
  client,
  closeClient: true,
});
```

### Expected Behavior

I believe changing [this signature](https://github.com/fastify/fastify-redis/blob/master/types/index.d.ts#L21) to `client: Redis | Cluster` would fix this issue.

**Comment by Uzlopak** [comment]
PR is welcome. Dont forget to add a typings test.
