### ISSUE TITLE
how to handle connection error

### ISSUE THREAD

**Issue by stefanocudini** [fastify/fastify-redis#170]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

what is the most correct way to handle redis connection errors, to have a simple human error log?

```js
...
const fastify = Fastify({logger});

fastify.ready(err => {
  if (err) {
    fastify.log.debug(`Redis Connection Error ${err.code}`)
  }
})

fastify.register(require('@fastify/redis'), {
  host: config.redis.hosts,
  password: config.redis.password
});
```

**Comment by mcollina** [comment]
What error are you getting right now?

**Comment by stefanocudini** [comment]
simply connection error to my redis instance.
I can't figure out for this error where I should put my try-catch to do these two things:
- show a log clearly indicating that the redis instance is unreachable
- try a reconnect to redis

the code above shows this error on run, if redis is unreachable, but I don't understand what is the best way to catch the error
```
/home/stefc/app/node_modules/fastify/fastify.js:541
        ? appendStackTrace(err, new AVVIO_ERRORS_MAP[err.code](err.message))
                                ^
FastifyError [Error]: fastify-plugin: Plugin did not start in time: '@fastify/redis'. You may have forgotten to call 'done' function or to resolve a Promise

...

 {
  code: 'FST_ERR_PLUGIN_TIMEOUT',
  statusCode: 500,
  cause: AvvioError [Error]: Plugin did not start in time: '@fastify/redis'. You may have forgotten to call 'done' function or to resolve a Promise
      at Timeout._onTimeout (/home/stefc/app/node_modules/avvio/plugin.js:122:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'AVV_ERR_READY_TIMEOUT',
    fn: <ref *1> [Function: fastifyRedis] {
      default: [Circular *1],
      fastifyRedis: [Circular *1],
      [Symbol(skip-override)]: true,
      [Symbol(fastify.display-name)]: '@fastify/redis',
      [Symbol(plugin-meta)]: { fastify: '4.x', name: '@fastify/redis' }
    }
  }
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kibertoad** [comment]
@stefanocudini Problem with redis is that it doesn't have built-in timeout functionality. You need to add it yourself. See how it is implemented using runWithTimeout here: https://github.com/lokalise/node-service-template/blob/main/src/infrastructure/healthchecks.ts

**Comment by stefanocudini** [comment]
> @stefanocudini Problem with redis is that it doesn't have built-in timeout functionality. You need to add it yourself. See how it is implemented using runWithTimeout here: https://github.com/lokalise/node-service-template/blob/main/src/infrastructure/healthchecks.ts

but I just want to catch the error: FST_ERR_PLUGIN_TIMEOUT, how can I do this?

**Comment by stefanocudini** [comment]
I'm try other ways... but nothing catch the exceptions

```js
const fastify = Fastify({logger});

fastify.setErrorHandler(function (error, request, reply) {
  fastify.log.debug(`Redis Connection Error setErrorHandler ${error.code}`)
})

fastify.addHook('onError', function (error, request, reply) {
  fastify.log.debug(`Redis Connection Error onError ${error.code}`)
})

fastify.register(require('@fastify/redis'), {
  host: config.redis.hosts,
  password: config.redis.password
});

```

**Comment by mcollina** [comment]
You might need to add some additional logging in https://github.com/fastify/fastify-redis/blob/master/index.js#L61-L99. 

Currently, this plugin assumes it can connect to the Redis instance. There is no way to "try again" if the connection fails or the time it tasks is over the time allotted.

**Comment by stefanocudini** [comment]
@mcollina  ok now it's clear to me!

I will try to send a PR.. Can you tell me if I can use part of the same code from the mongo plugin?
Penso che il plugin mongo sia più evoluto di redis

**Comment by mcollina** [comment]
Sure reuse whatever you find useful. Fastify is mainly driven by community contributions, and different modules attract different level of contributions.

**Comment by agjs** [comment]
@stefanocudini - I'm having the same issue. Did you figure this one out yet? If you need help, I'm happy to pair up and do a PR on this one.

**Comment by Eomm** [comment]
Do it solve? https://github.com/fastify/fastify-redis/pull/177

**Comment by stefanocudini** [comment]
the fix in #177 solve a different problem, close redis connetion when fastify closed.
This issue is about the opposite problem: Redis connection closed that crashes the fastify app.

The main problem, as explained above, is that there isn't a way to catch errors of this type on the fastify side.
This is an unsolved problem

**Comment by stefanocudini** [comment]
> Do it solve? #177

the fix in #177 (adding a new option) solve a different problem, close redis connetion when fastify closed.
This issue is about the opposite problem: Redis connection closed that crashes the fastify app.

The main problem, as explained above, is that there isn't a way to catch errors of this type on the fastify side.
This is an unsolved problem

**Comment by stefanocudini** [comment]
> > but I just want to catch the error: FST_ERR_PLUGIN_TIMEOUT, how can I do this?
> 
> ```
> const app = require('fastify')({ logger: true, pluginTimeout: 1000 })
> 
> app.register(function plugin (app, opts, next) {
>   // don't call next()
> }).after(function (err) {
>   console.log({ err })// timeout error
> })
> 
> app.ready()
> ```

unfortunately this doesn't cover the case where the connection to redis drops after plugin is registration..

**Comment by stefanocudini** [comment]
> @stefanocudini - I'm having the same issue. Did you figure this one out yet? If you need help, I'm happy to pair up and do a PR on this one.

a partial solution for my case is it:
```
fastify.register(require('@fastify/redis'), {
  host: config.redis.hosts,
  password: config.redis.password,
  maxRetriesPerRequest: 100,
  retryDelayOnFailover: 500,
  closeClient: true, // force to close the redis connection when app stopped
})
.after(err => {
  const {redis} = fastify;
  if (err) {
    fastify.log.error('Redis connection error')
  }
  redis.on('error', function(err) {
    fastify.log.error('Redis connection error')
  })
})```

@Eomm thank you very much for your suggestion. I think solved this way with the latest version of the plugin and using some additional parameters

**Comment by 2ico** [comment]
I was trying to fix the same issue but I get this:

```
    redis.on('error', function (err) {
          ^


TypeError: redis2.on is not a function
```

**Comment by 2ico** [comment]
Edit: my bad, I should include the namespace

```
redis.NAMESPACE.on('error',...)
```
