### ISSUE TITLE
Include option to choose client creation method (node-redis or ioredis)

### ISSUE THREAD

**Issue by rhighs** [fastify/fastify-redis#175]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Since ioredis supports node-redis configuration objects it would be nice to include a plugin option that enables developers to create a client via [ioredis createClient(...)](https://github.com/luin/ioredis/blob/92aefaac13f42ad14986fde47c640ff8edc415ef/lib/Redis.ts#L76) rather than `new Redis()`

### Motivation

Compatibility with node-redis config objects, although for the sake of clarity it might just be fine to pass a ready made ioredis client to fastify-redis at init time. 

### Example

```javascript
const fastifyRedis = require('@fastify/redis') 

const nodeRedisConfig = {
  socket: {
    host: '127.0.0.1',
    port: 6379, // Redis port
    family: 4   // 4 (IPv4) or 6 (IPv6) 
  }
  password: '***'
}

fastify.register(require('@fastify/redis'), { 
  ...nodeRedisConfig
  clientCreationMethod: fastifyRedis.creationMethod.NODE_REDIS
})
```

```javascript
// fastify-redis/indes.js
....

module.exports = fp(fastifyRedis, {
  fastify: '4.x',
  name: '@fastify/redis'
})
module.exports.default = fastifyRedis
module.exports.fastifyRedis = fastifyRedis

module.exports.creationMethod = {
  NODE_REDIS: "node-redis",
  IOREDIS: "io-redis"
}
```

**Comment by climba03003** [comment]
Why can't you create yourself if you want to use different client?

```js
const ioredis = require('ioredis')
const nodeRedisConfig = {
  socket: {
    host: '127.0.0.1',
    port: 6379, // Redis port
    family: 4   // 4 (IPv4) or 6 (IPv6) 
  }
  password: '***'
}

fastify.register(require('@fastify/redis'), { 
  client: ioredis.createClient({
    ...nodeRedisConfig,
    creationMethod: 'node-redis'
  })
})
```

**Comment by rhighs** [comment]
Yep, silly me it's way better like this, closing... Thank you! @climba03003
