### ISSUE TITLE
Get keys by pattern

### ISSUE THREAD

**Issue by anistark** [fastify/fastify-redis#183]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Redis allows fetching data by pattern search like `KEYS pattern`.

Requesting feature to support `redis.get` with wildcard support:
1. `key-*` to search for `keys-1`, `keys-qwerty`, etc.
2. `key-?` to search for `keys-1`, `keys-2`, ....

### Motivation

Already supported by redis nodejs library.

Example code:
```js
client.keys('key-*', function (err, keys) {
    ...
});
```

### Example

Should look something like: `fastify.redis.get('key-*')`

**Comment by Uzlopak** [comment]
We dont add any get-method to the fastify.redis attribute. fastify.redis is a ioredis client. So you should be able to make all the calls you like.

**Comment by anistark** [comment]
> We dont add any get-method to the fastify.redis attribute. fastify.redis is a ioredis client. So you should be able to make all the calls you like.

Got it. `fastify.redis.keys("key-*)` works 🎉
