### ISSUE TITLE
new feature | add option to create pub sub

### ISSUE THREAD

**Issue by fas3r** [fastify/fastify-redis#35]
Hello, 

Do you think it could be possible to add an option that create automatically a pub/sub instance. 

It would return something like this once register:

```
fastify.redis[namespace] = {
   pub: io-redisInstance
   sub: io-redisInstance
}
```

It could be an option own by the plugin, as the options that we provide to the plugin are given to io-redis client.

Something like : 

```
fastify.register(require('fastify-redis'), { pubsub: true, host: 'localhost', port: 6379 })
```

And if we want to use different hosts it could be like : 

```

const hosts = {
    pub: { 
          host: ...,
          port: ...,
          ....other_io_redis_options
    }, 
    sub: {
         host: ....,
         port: ....,
         ....other_io_redis_options
    } 
}

fastify.register(require('fastify-redis'), { pubsub: true, hosts: hosts })
```

It would prevent to have namespace like `pubNamespace`, `subNamespace`. 

It would also prevent us to import again io-redis to provide instances in case we need pub/sub.

I use io-redis and try to move away from it, meaning, to use it with your plugin directly and I thought it could be cool to have this feature.

I'm can prepare a pull request if you want, I prefer to ask first 

Thanks

**Comment by mcollina** [comment]
That’s definitely a common pattern, however I thought the namespaces solved this. Why are they not enough?

**Comment by fas3r** [comment]
Hello @mcollina ,

It does, but as pub/sub comes as a pair, we could assume that namespace return both as shown in the potential solution.

Thanks.

**Comment by mcollina** [comment]
The problem is that the `pub` connection can be used for everything, while the `sub` one cannot take any more commands after subscribe.

I don't see the advantage of this proposed approach.

**Comment by fas3r** [comment]
Hello @mcollina ,

ok no problem. 

Thanks
