### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [fastify/fastify-redis#38]
## 🚀 Feature Proposal

Add an index.d.ts with Typescript type definitions.

## Motivation

To use it on Typescript projects.

I can do a PR for this if you are ok with it.

**Comment by mcollina** [comment]
A PR would be awesome!

**Comment by ricardo-devis-agullo** [comment]
Done! :)

**Comment by ifaisalalam** [comment]
@mcollina This issue can be closed as TS definitions have been added in PR #46

**Comment by mcollina** [comment]
thanks!
