### ISSUE TITLE
Passing only a URL to the redis instance is not supported

### ISSUE THREAD

**Issue by zuck** [fastify/fastify-redis#40]
## 🐛 Bug Report

Currenlty, passing only a URL to the Redis server is not supported by `fastify-redis` but it's supported by `ioredis` and other Node-based Redis clients, e.g.:

```js
var urlRedis = new Redis('redis://user:password@redis-service.com:6379/')
```

## To Reproduce

```js
fastify.regster(require('fastify-redis'), 'redis://user:password@redis-service.com:6379/')
```

## Expected behavior

A working connection to the Redis server.

An error is generated instead, saying that `Cannot read property 'options' of undefined`.

**Comment by mcollina** [comment]
Would you like to send us a PR?
Il 11 nov 2019, 19:30 +0000, Emanuele Bertoldi <notifications@github.com>, ha scritto:
