### ISSUE TITLE
FST_ERR_PROMISE_NOT_FULLFILLED

### ISSUE THREAD

**Issue by jenokizm** [fastify/fastify-redis#41]
Why, if use streams sample i see error in console?
`await fastify.redis.xadd(['my awesome fastify stream name', '*', 'hello', 'fastify is awesome']);`

> "type":"FastifyError",
> "message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204",

but xadd worked for me.

**Comment by mcollina** [comment]
Can you upload a full example?

**Comment by jenokizm** [comment]
ok. i have get request routing
```
fastify.get('/setsttest', async (req, reply) => {
    var idres = await fastify.redis.xadd(['my awesome fastify stream name', '*', 'hello', 'fastify is awesome']);
    console.log(idres);
})
```

**Comment by jenokizm** [comment]
Ahh) I get the point. You need to give something to an HTML page like
`reply.send(idres);`
now there is no error

**Comment by mcollina** [comment]
no worries!
