### ISSUE TITLE
Supplied client should be closed when Fastify shuts down

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-redis#64]
When specifying your own Redis instance, e.g.:

```js
const Redis = require('ioredis')
const redis = new Redis('redis://example.com')
fastify.register(require('fastify-redis'), { client: redis })
```

That client will not be closed when Fastify shuts down. This is surprising because the user is saying "here, Fastify, handle this for me" but we don't.

I see that this was implemented in https://github.com/fastify/fastify-redis/pull/25 but I don't think the justification is sufficient. Test run time shouldn't dictate feature set.

**Comment by mcollina** [comment]
I think the principle we follow everywhere is: if we create a db connection, we close that db connection; if the user creates a db connection, the user close the db connection. It clearly splits the responsibility. We can definitely add a snippet to call `fastify.onClose(() => client.close())` or something similar.

**Comment by mdboop** [comment]
Just a thought, but isn't there a third option to, well, make it optional?

```js
const fastify = require('fastify')()
const redis = require('redis').createClient({ host: 'localhost', port: 6379 })

fastify.register(require('fastify-redis'), { client: redis, close: true })
```

Although, I think I agree that adding a snippet and leaving it to the user to handle is simpler and makes the most sense.

**Comment by mcollina** [comment]
That also works for me.

**Comment by jsumners** [comment]
I'm okay with requiring an extra option to specify that the plugin should close the client. But what is the point of using `fastify-redis` if it doesn't manage the connection? Without it managing the connection, all it is doing is adding a decorator and that is easy enough for anyone to do: `fastify.decorate('redis', redis)`.

When I added this feature in https://github.com/fastify/fastify-redis/pull/11/files the point was so that the client could be reused with `fastify-caching`, and any other scenario anyone could think of, while letting `fastify-redis` do the smart things around the Fastify life cycle.

I looked at `fastify-postgres` and `fastify-mysql` and it looks like we do not accept pre-created instances in either of those. Which other plugins are we saying follows the pattern of "if we didn't create the connection we don't close it"?

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-mongodb/blob/13572f9fba9030de480629b698c1a8a251a8356e/index.js#L15-L18 here it is.

**Comment by jsumners** [comment]
Okay, I can see that I added the same feature in https://github.com/fastify/fastify-mongodb/pull/17 and it was later adjusted in https://github.com/fastify/fastify-mongodb/pull/41.

I'm disappointed in myself for having missed these changes. I think they are not correct for the above outlined reasons.

Regardless, I'll submit a PR to support `close: true`.

**Comment by mcollina** [comment]
Well, we can change these :D
