### ISSUE TITLE
No option for closing provided client in namespace

### ISSUE THREAD

**Issue by gkampitakis** [fastify/fastify-redis#75]
## 🐛 Bug Report

Hey 👋,I noticed if you provide a `Redis` client in namespace there is no option for closing the client as you have in a non namespace instance.

## To Reproduce

```js
if (namespace) {
    ....
    if (!client) {
      ....
      fastify.addHook('onClose', closeNamedInstance)
    }

    fastify.redis[namespace] = client
}
```

## Expected behavior

I would expect to have the same snippet as in non namespace

```js
if (options.closeClient === true) {
        fastify.addHook('onClose', closeNamedInstance)
}
```

Sorry If I understood it wrong but this is what I would expect.  If that's the case though seems a quick fix and I could create a pr for it.

**Comment by mcollina** [comment]
I think you are right! Would you like to send a PR?

**Comment by gkampitakis** [comment]
> I think you are right! Would you like to send a PR?

Happy to :D

**Comment by mcollina** [comment]
shipped!
