### ISSUE TITLE
[Question] ReplyError: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by gkampitakis** [fastify/fastify-redis#78]
## 🐛 Bug Report

It's more of a question, not sure if it is a bug. I noticed when you don't provide password authentication , ioredis continuously logs 

```
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
```

and fastify server is still running. Should this error be handled somehow by the plugin or give the option of shutting down fastify on error ? 

## To Reproduce

Try to connect to redis without provided authentication.

## Expected behavior

Should fastfiy stop working ? 

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
I think so, would you like to send a PR to handle this?

**Comment by gkampitakis** [comment]
It seems to be an ioredis issue and not something this plugin should handle. This is my understanding from this open [issue in ioredis](https://github.com/luin/ioredis/issues/1146). Sorry for not fidning it earlier but I was running a fastify application and i noticed this and another node service which was "behaving" correctly so I assumed wrong 😓 . I can close his issue if you agree

**Comment by mcollina** [comment]
Good analysis, thanks!
